# Generated by Django 3.1.7 on 2021-03-04 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_auto_20210304_1802'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='account',
            new_name='bank',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.company', verbose_name='Фирма'),
        ),
    ]
