# Generated by Django 3.1.7 on 2021-03-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_auto_20210310_0623'),
        ('bank', '0004_auto_20210309_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='bank.bank', verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='Company.company', verbose_name='Фирма'),
        ),
    ]
