# Generated by Django 3.1.7 on 2021-03-25 07:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20210314_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='token',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='login_bank',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='password_bank',
            field=models.CharField(default=datetime.datetime(2021, 3, 25, 7, 41, 4, 416770, tzinfo=utc), max_length=255, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
