# Generated by Django 3.1.7 on 2021-04-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20210325_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
