# Generated by Django 3.1.7 on 2021-05-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_auto_20210512_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mail', models.DateField()),
                ('title_mail', models.CharField(max_length=255, verbose_name='Заголовок письма')),
                ('content_mail', models.TextField()),
                ('sender_mail', models.CharField(max_length=255, verbose_name='Отправитель')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankaccounts', to='bank.bankaccount', verbose_name='Аккаунт')),
            ],
        ),
    ]
