# Generated by Django 3.1.7 on 2021-05-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_mailbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbank',
            name='content_mail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mailbank',
            name='date_mail',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mailbank',
            name='sender_mail',
            field=models.CharField(max_length=255, null=True, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='mailbank',
            name='title_mail',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок письма'),
        ),
    ]
