# Generated by Django 3.1.7 on 2021-07-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_auto_20210527_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='in_block',
            field=models.BooleanField(null=True),
        ),
    ]
