# Generated by Django 3.1.7 on 2021-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_bankaccount_in_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='in_block',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
