# Generated by Django 3.1.7 on 2021-08-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_auto_20210727_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='in_block',
            field=models.BooleanField(default=False, verbose_name='В блоке'),
        ),
    ]
