# Generated by Django 3.1.7 on 2021-02-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('inn', models.CharField(max_length=30, verbose_name='ИНН')),
                ('date_of_birth', models.CharField(max_length=10, verbose_name='Дата рождения')),
                ('place_of_birth', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('id_passport', models.CharField(max_length=10, verbose_name='Номер паспорта')),
                ('date_of_issue', models.CharField(max_length=10, verbose_name='Дата выдачи')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('department_сode', models.CharField(max_length=7, verbose_name='Код подразделения')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.CharField(max_length=255, verbose_name='Дом')),
            ],
        ),
    ]
