# Generated by Django 3.1.7 on 2021-03-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Director', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Директор', 'verbose_name_plural': 'Директора'},
        ),
    ]
