# Generated by Django 3.1.7 on 2021-03-16 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Director', '0002_auto_20210302_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
    ]
