# Generated by Django 3.1.7 on 2021-03-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Director', '0002_auto_20210302_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фирмы')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('okved', models.CharField(max_length=255, verbose_name='ОКВЭД')),
                ('legal_address', models.CharField(max_length=255, verbose_name='Юр.Адресс')),
                ('legal_city', models.CharField(max_length=255, verbose_name='Юр.Город')),
                ('date_of_application', models.CharField(max_length=255, verbose_name='Дата подачи')),
                ('registration_date', models.CharField(max_length=255, verbose_name='Дата регистрации')),
                ('charter_number', models.CharField(max_length=50, verbose_name='Номер устава')),
                ('directors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Director.director', verbose_name='Директор')),
            ],
        ),
    ]
