# Generated by Django 3.1.7 on 2021-03-04 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('Company', '0002_company_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bank',
        ),
        migrations.AddField(
            model_name='company',
            name='bank1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank', verbose_name='Банк'),
        ),
    ]
