# Generated by Django 3.1.7 on 2021-03-09 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210304_1802'),
        ('Company', '0003_auto_20210304_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bank1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='bank.bank', verbose_name='Банк'),
        ),
    ]
