# Generated by Django 3.1.7 on 2021-03-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20210309_1223'),
        ('Company', '0005_auto_20210309_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bank1',
        ),
        migrations.AddField(
            model_name='company',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankaccount', to='bank.bankaccount', verbose_name='Банк'),
        ),
    ]
