# Generated by Django 3.1.7 on 2021-03-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_auto_20210310_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='bank',
            new_name='bankaccount',
        ),
    ]
