# Generated by Django 3.1.7 on 2021-03-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0008_auto_20210310_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Фирма', 'verbose_name_plural': 'Фирмы'},
        ),
    ]
