# Generated by Django 3.1.7 on 2021-04-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20210325_0741'),
        ('Company', '0010_company_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bankaccount',
        ),
        migrations.AddField(
            model_name='company',
            name='bankaccount',
            field=models.ManyToManyField(blank=True, null=True, related_name='bankaccount', to='bank.BankAccount', verbose_name='Банк'),
        ),
    ]
