# Generated by Django 3.1.7 on 2021-04-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20210325_0741'),
        ('Company', '0011_auto_20210406_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bankaccount',
        ),
        migrations.AddField(
            model_name='company',
            name='bankaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankaccount', to='bank.bankaccount', verbose_name='Банк'),
        ),
    ]
