# Generated by Django 3.1.7 on 2021-04-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0013_auto_20210406_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Название на латинице'),
        ),
    ]
