# Generated by Django 3.1.7 on 2021-05-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0014_auto_20210406_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bankaccount',
        ),
    ]
